<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)../../Tests.Common.props" />

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EggLedger.Desktop.csproj" />
    <ProjectReference Include="..\..\EggLedger.Domain\EggLedger.Domain.csproj" />
  </ItemGroup>

</Project>
