CREATE TABLE IF NOT EXISTS report_groups (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    name TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE reports ADD COLUMN group_id TEXT NOT NULL DEFAULT '';
