-- Phase 3: server-side mission/report/settings storage, keyed by Discord user.
-- Mirrors the desktop SQLite schema (final consolidated shape) plus a discord_id
-- column so the shared Postgres database is multi-tenant. Column names are the
-- snake_case JSON property names the PostgresIndexedDb adapter materializes rows
-- from, so they must match the Row record JsonPropertyName values exactly.

CREATE TABLE IF NOT EXISTS el_mission (
    discord_id       TEXT    NOT NULL,
    player_id        TEXT    NOT NULL,
    mission_id       TEXT    NOT NULL,
    start_timestamp  DOUBLE PRECISION NOT NULL,
    complete_payload BYTEA   NOT NULL,
    mission_type     BIGINT  NOT NULL DEFAULT -1,
    ship             BIGINT  NOT NULL DEFAULT -1,
    duration_type    BIGINT  NOT NULL DEFAULT -1,
    level            BIGINT  NOT NULL DEFAULT -1,
    capacity         BIGINT  NOT NULL DEFAULT -1,
    nominal_capacity BIGINT  NOT NULL DEFAULT 0,
    is_dub_cap       BOOLEAN NOT NULL DEFAULT FALSE,
    is_bugged_cap    BOOLEAN NOT NULL DEFAULT FALSE,
    target           BIGINT  NOT NULL DEFAULT -1,
    return_timestamp DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (discord_id, player_id, mission_id)
);
CREATE INDEX IF NOT EXISTS idx_el_mission_player      ON el_mission(discord_id, player_id);
CREATE INDEX IF NOT EXISTS idx_el_mission_player_ship ON el_mission(discord_id, player_id, ship);
CREATE INDEX IF NOT EXISTS idx_el_mission_player_ts   ON el_mission(discord_id, player_id, start_timestamp);

-- Browser store keys backup on player_id (one row per player). JSON props:
-- player_id, backed_up_at, payload.
CREATE TABLE IF NOT EXISTS el_backup (
    discord_id   TEXT    NOT NULL,
    player_id    TEXT    NOT NULL,
    backed_up_at DOUBLE PRECISION NOT NULL,
    payload      BYTEA   NOT NULL,
    PRIMARY KEY (discord_id, player_id)
);

CREATE TABLE IF NOT EXISTS el_artifact_drops (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    discord_id  TEXT    NOT NULL,
    mission_id  TEXT    NOT NULL,
    player_id   TEXT    NOT NULL,
    drop_index  BIGINT  NOT NULL,
    artifact_id BIGINT  NOT NULL,
    spec_type   TEXT    NOT NULL,
    level       BIGINT  NOT NULL,
    rarity      BIGINT  NOT NULL,
    quality     DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (discord_id, mission_id, player_id, drop_index)
);
CREATE INDEX IF NOT EXISTS idx_el_drops_player        ON el_artifact_drops(discord_id, player_id);
CREATE INDEX IF NOT EXISTS idx_el_drops_player_rarity ON el_artifact_drops(discord_id, player_id, rarity);
CREATE INDEX IF NOT EXISTS idx_el_drops_player_artifact ON el_artifact_drops(discord_id, player_id, artifact_id);
CREATE INDEX IF NOT EXISTS idx_el_drops_player_level  ON el_artifact_drops(discord_id, player_id, level);

CREATE TABLE IF NOT EXISTS el_settings (
    discord_id TEXT NOT NULL,
    key        TEXT NOT NULL,
    value      TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (discord_id, key)
);

CREATE TABLE IF NOT EXISTS el_reports (
    discord_id             TEXT    NOT NULL,
    id                     TEXT    NOT NULL,
    account_id             TEXT    NOT NULL,
    name                   TEXT    NOT NULL,
    subject                TEXT    NOT NULL,
    mode                   TEXT    NOT NULL,
    display_mode           TEXT    NOT NULL,
    group_by               TEXT    NOT NULL,
    time_bucket            TEXT,
    custom_bucket_n        BIGINT,
    custom_bucket_unit     TEXT,
    filters                TEXT    NOT NULL DEFAULT '{"and":[],"or":[]}',
    grid_x                 BIGINT  NOT NULL DEFAULT 0,
    grid_y                 BIGINT  NOT NULL DEFAULT 0,
    grid_w                 BIGINT  NOT NULL DEFAULT 1,
    grid_h                 BIGINT  NOT NULL DEFAULT 1,
    weight                 TEXT    NOT NULL DEFAULT 'LOW',
    sort_order             BIGINT  NOT NULL DEFAULT 0,
    created_at             BIGINT  NOT NULL,
    updated_at             BIGINT  NOT NULL,
    color                  TEXT    NOT NULL DEFAULT '#6366f1',
    description            TEXT    NOT NULL DEFAULT '',
    chart_type             TEXT    NOT NULL DEFAULT 'bar',
    value_filter_op        TEXT    NOT NULL DEFAULT '',
    value_filter_threshold DOUBLE PRECISION NOT NULL DEFAULT 0,
    group_id               TEXT    NOT NULL DEFAULT '',
    normalize_by           TEXT    NOT NULL DEFAULT 'none',
    label_colors           TEXT    NOT NULL DEFAULT '',
    secondary_group_by     TEXT    NOT NULL DEFAULT '',
    unfilled_color         TEXT    NOT NULL DEFAULT '',
    family_weight          TEXT    NOT NULL DEFAULT '',
    menno_enabled          BOOLEAN NOT NULL DEFAULT FALSE,
    menno_compare_mode     TEXT    NOT NULL DEFAULT 'side_by_side',
    min_sample_size        BIGINT  NOT NULL DEFAULT 0,
    PRIMARY KEY (discord_id, id)
);
CREATE INDEX IF NOT EXISTS idx_el_reports_account ON el_reports(discord_id, account_id);

CREATE TABLE IF NOT EXISTS el_report_groups (
    discord_id TEXT NOT NULL,
    id         TEXT NOT NULL,
    account_id TEXT NOT NULL,
    name       TEXT NOT NULL,
    sort_order BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (discord_id, id)
);
