-- DataProtection key ring, persisted to Postgres so the cookie-auth keys survive
-- container redeploys (otherwise every deploy invalidates all sessions). One row per
-- key XML element; the custom IXmlRepository reads/writes friendly_name + xml.
CREATE TABLE IF NOT EXISTS data_protection_keys (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    friendly_name TEXT,
    xml           TEXT NOT NULL
);
